### ISSUE TITLE
Res-face slim

### ISSUE THREAD

**Issue by sabrinatuli** [zlmo/face_detection#3]
Hello,
Thanks for your implementation of yolov2 and yolov3 with WiderFace for face detection. I want to know more about your res-face slim approach more in details. Have you implemented it in pytorch? 
Thanks in advance

**Comment by zlmo** [comment]
Hi,
You can find the detail implementation in the /cfg/resface_slim.cfg, and sorry that I did't implement it in pytorch. If you want to use pytorch to realize small face detection, maybe you can try just using the original yolov3 and widerface dataset, it's good enough.
